import React,{useEffect,useState}from'react';import{createClient}from'@supabase/supabase-js';import{BookOpen,Brain,LayoutDashboard,LogOut,Menu,Search,Stethoscope,Trophy,Upload,Users,Clock,CheckCircle,PlayCircle,X}from'lucide-react';
const url=import.meta.env.VITE_SUPABASE_URL, key=import.meta.env.VITE_SUPABASE_ANON_KEY;const supabase=createClient(url,key);
const demoStats={tests:12,score:84,points:420,streak:7};
function App(){const[sess,setSess]=useState(null),[profile,setProfile]=useState(null),[page,setPage]=useState('dashboard'),[loading,setLoading]=useState(true);
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSess(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSess(s));return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(sess)loadProfile()},[sess]);
async function loadProfile(){const{data}=await supabase.from('profiles').select('*').eq('id',sess.user.id).maybeSingle();setProfile(data)}
if(loading)return <div className="center"><div className="spinner"/><p>Loading MedVerse…</p></div>;
if(!sess)return <Auth/>;
return <div className="app"><Sidebar page={page} setPage={setPage} profile={profile}/><main><Topbar profile={profile}/>{page==='dashboard'&&<Dashboard profile={profile} setPage={setPage}/>}
{page==='tests'&&<Tests/>}{page==='materials'&&<Materials/>}{page==='ospe'&&<OSPE/>}{page==='points'&&<Points profile={profile}/>} {page==='profile'&&<Profile profile={profile}/>}
</main></div>}
function Auth(){const[email,setEmail]=useState(''),[pass,setPass]=useState(''),[name,setName]=useState(''),[signup,setSignup]=useState(false),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
async function go(e){e.preventDefault();setBusy(true);setMsg('');let r=signup?await supabase.auth.signUp({email,password:pass,options:{data:{full_name:name}}}):await supabase.auth.signInWithPassword({email,password:pass});setBusy(false);if(r.error)setMsg(r.error.message);else if(signup)setMsg('Account created. Check your email if confirmation is enabled.')}
return <div className="auth"><div className="auth-card"><div className="brand big"><div className="logo"><Stethoscope/></div><div><b>MedVerse</b><small>Medical learning, simplified.</small></div></div><h1>{signup?'Create your account':'Welcome back'}</h1><p className="muted">{signup?'Start your learning journey.':'Sign in to continue your study.'}</p><form onSubmit={go}>{signup&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={pass} onChange={e=>setPass(e.target.value)} required/><button className="primary wide" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Sign in'}</button></form>{msg&&<div className="notice">{msg}</div>}<button className="link" onClick={()=>setSignup(!signup)}>{signup?'Already have an account? Sign in':'New to MedVerse? Create account'}</button></div></div>}
function Sidebar({page,setPage,profile}){let items=[['dashboard','Dashboard',LayoutDashboard],['tests','Tests & MCQs',Brain],['materials','Study Materials',BookOpen],['ospe','OSPE Practice',Stethoscope],['points','Pearl Points',Trophy]];return <aside><div className="brand"><div className="logo"><Stethoscope size={22}/></div><div><b>MedVerse</b><small>Medical Learning</small></div></div><nav>{items.map(([id,t,I])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><I size={19}/>{t}</button>)}</nav><div className="side-bottom"><button onClick={()=>setPage('profile')} className={page==='profile'?'active':''}><Users size={18}/>Profile</button><button onClick={()=>supabase.auth.signOut()}><LogOut size={18}/>Sign out</button></div></aside>}
function Topbar({profile}){return <header><div><span className="eyebrow">STUDENT PORTAL</span><h2>Good to see you, {profile?.full_name?.split(' ')[0]||'Student'} 👋</h2></div><div className="avatar">{(profile?.full_name||'S').slice(0,1).toUpperCase()}</div></header>}
function Dashboard({profile,setPage}){return <section className="content"><div className="hero"><div><span className="pill">MEDVERSE • CONNECTED</span><h1>Your medical learning hub.</h1><p>Study smarter with tests, resources, OSPE practice and progress tracking.</p><button className="primary" onClick={()=>setPage('tests')}><PlayCircle size={18}/>Start a test</button></div><div className="hero-art"><Stethoscope size={88}/></div></div><div className="stats">{[['Tests completed',demoStats.tests],['Average score',demoStats.score+'%'],['Pearl Points',profile?.pearl_points||demoStats.points],['Study streak',demoStats.streak+' days']].map(([a,b])=><div className="stat" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><div className="section-head"><h3>Quick access</h3></div><div className="grid3"><Quick icon={Brain} title="Tests & MCQs" text="Practice published question sets" onClick={()=>setPage('tests')}/><Quick icon={BookOpen} title="Study Materials" text="Browse your learning library" onClick={()=>setPage('materials')}/><Quick icon={Stethoscope} title="OSPE Practice" text="Train with clinical stations" onClick={()=>setPage('ospe')}/></div></section>}
function Quick({icon:I,title,text,onClick}){return <button className="feature" onClick={onClick}><div className="iconbox"><I size={22}/></div><div><b>{title}</b><p>{text}</p></div><span>→</span></button>}
function Tests(){const[data,setData]=useState([]),[q,setQ]=useState(''),[busy,setBusy]=useState(true),[open,setOpen]=useState(null);useEffect(()=>{supabase.from('tests').select('*').eq('is_published',true).order('created_at',{ascending:false}).then(({data})=>{setData(data||[]);setBusy(false)})},[]);let shown=data.filter(x=>x.title.toLowerCase().includes(q.toLowerCase()));return <section className="content"><div className="section-head"><div><span className="eyebrow">ASSESSMENT</span><h1>Tests & MCQs</h1></div><div className="search"><Search size={17}/><input placeholder="Search tests…" value={q} onChange={e=>setQ(e.target.value)}/></div></div>{busy?<Loader/>:shown.length?<div className="cards">{shown.map(t=><div className="testcard" key={t.id}><div className="test-icon"><Brain/></div><h3>{t.title}</h3><p>{t.description||'Practice test from the MedVerse question bank.'}</p><div className="meta"><span><Clock size={15}/>{t.duration_minutes} min</span><span><CheckCircle size={15}/>Published</span></div><button className="primary wide" onClick={()=>setOpen(t)}>Start test</button></div>)}</div>:<Empty text="No published tests yet. Add tests from your teacher/admin account."/>}{open&&<TestModal test={open} close={()=>setOpen(null)}/>}</section>}
function TestModal({test,close}){const[qs,setQs]=useState([]),[answers,setAnswers]=useState({}),[done,setDone]=useState(false);useEffect(()=>{supabase.from('test_questions').select('question_id,question_order,questions(id,question_text,explanation,correct_answer,question_type)').eq('test_id',test.id).order('question_order').then(async({data})=>{let ids=(data||[]).map(x=>x.questions).filter(Boolean);if(ids.length){const{data:opts}=await supabase.from('question_options').select('*').in('question_id',ids.map(x=>x.id));ids=ids.map(x=>({...x,options:(opts||[]).filter(o=>o.question_id===x.id)}))}setQs(ids)})},[test]);async function submit(){let score=0;qs.forEach(q=>{if(answers[q.id]&&answers[q.id]===q.correct_answer)score++});if(qs.length){await supabase.from('attempts').insert({test_id:test.id,student_id:(await supabase.auth.getUser()).data.user.id,score,status:'submitted',submitted_at:new Date().toISOString()})}setDone(true)}return <div className="overlay"><div className="modal"><button className="close" onClick={close}><X/></button><span className="eyebrow">TEST</span><h2>{test.title}</h2>{done?<div className="result"><Trophy size={44}/><h2>Submitted</h2><p>You scored {qs.filter(q=>answers[q.id]===q.correct_answer).length} / {qs.length}</p><button className="primary" onClick={close}>Done</button></div>:<><div className="questions">{qs.map((q,i)=><div className="question" key={q.id}><b>{i+1}. {q.question_text}</b>{q.options?.map(o=><label key={o.id}><input type="radio" name={q.id} value={o.option_key} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/>{o.option_key}. {o.option_text}</label>)}</div>)}</div><button className="primary wide" onClick={submit} disabled={!qs.length}>Submit test</button></>}</div></div>}
function Materials(){const[data,setData]=useState([]);useEffect(()=>{supabase.from('materials').select('*,subjects(name)').eq('is_published',true).order('created_at',{ascending:false}).then(({data})=>setData(data||[]))},[]);return <section className="content"><div className="section-head"><div><span className="eyebrow">LIBRARY</span><h1>Study Materials</h1></div><button className="secondary"><Upload size={17}/>Upload</button></div>{data.length?<div className="cards">{data.map(m=><div className="material" key={m.id}><div className="material-icon"><BookOpen/></div><div><h3>{m.title}</h3><p>{m.description||'Study resource'} </p><small>{m.subjects?.name||'General'} • {m.file_type||'Resource'}</small></div></div>)}</div>:<Empty text="No published study materials yet."/>}</section>}
function OSPE(){const[data,setData]=useState([]);useEffect(()=>{supabase.from('ospe_stations').select('*,subjects(name)').eq('is_published',true).order('created_at',{ascending:false}).then(({data})=>setData(data||[]))},[]);return <section className="content"><span className="eyebrow">CLINICAL SKILLS</span><h1>OSPE Practice</h1><p className="muted">Practice stations and build confidence before your assessment.</p>{data.length?<div className="cards">{data.map(x=><div className="testcard" key={x.id}><div className="test-icon"><Stethoscope/></div><h3>{x.title}</h3><p>{x.instructions||'Clinical station practice.'}</p><div className="meta"><span><Clock size={15}/>{x.duration_minutes} min</span><span>{x.subjects?.name||'Clinical'}</span></div><button className="primary wide">Practice station</button></div>)}</div>:<Empty text="No published OSPE stations yet."/>}</section>}
function Points({profile}){return <section className="content"><div className="hero compact"><div><span className="pill">REWARDS</span><h1>Pearl Points</h1><p>Keep learning and build your points balance.</p></div><Trophy size={80}/></div><div className="points-big"><strong>{profile?.pearl_points||0}</strong><span>PEARL POINTS</span></div></section>}
function Profile({profile}){return <section className="content"><span className="eyebrow">ACCOUNT</span><h1>Profile</h1><div className="profile-card"><div className="avatar large">{(profile?.full_name||'S').slice(0,1).toUpperCase()}</div><div><h2>{profile?.full_name||'Student'}</h2><p className="muted">Academic year: {profile?.academic_year||'Not set'}</p><p className="muted">Role: {profile?.role||'student'}</p></div></div></section>}
function Loader(){return <div className="center small"><div className="spinner"/></div>}function Empty({text}){return <div className="empty"><BookOpen size={30}/><p>{text}</p></div>}
export default App;
